// <auto-generated />
using Commerce.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Commerce.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231202181413_addImageUrlToProduct")]
    partial class addImageUrlToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Commerce.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Elektronik"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Moda"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Sağlık"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Kitap"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Spor"
                        });
                });

            modelBuilder.Entity("Commerce.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Mikro kenarlı ekranıyla ince ve hafif - Hafif tasarımıyla her yere taşıyabileceğiniz bu bilgisayarın titremesiz ve mikro kenarlı ekranı daha konforlu görüntüleme deneyimi sunar.",
                            ImageUrl = "",
                            Price = 9499.0,
                            Title = "HP 15s Dizüstü Bilgisayar, 15.6'' FHD IPS, Intel Core i3-1215U, 8 GB Ram, 256 GB SSD, FreeDOS, Kömür Grisi, 6G0H5EA"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Evde, okulda, işte veya nerede olursanız olun, düzeninizi koruyun ve uygulamalarınızı uyumlu ve sorunsuz bir şekilde çalıştırın.",
                            ImageUrl = "",
                            Price = 9999.0,
                            Title = "Acer Aspire 3 A315-58 Dizüstü Bilgisayar, Intel i5-1135G7 İşlemci, 8GB Ram, 256GB SSD, 15,6\" FHD IPS Ekran"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Evde, okulda, işte veya nerede olursanız olun, düzeninizi koruyun ve uygulamalarınızı uyumlu ve sorunsuz bir şekilde çalıştırın.",
                            ImageUrl = "",
                            Price = 8299.0,
                            Title = "ASUS Notebook Laptop X515EA-BQ868 ,FHD Ekran, Intel Core i3-1115G4 İşlemci,Intel® UHD Graphics, 4GB RAM, 256GB SSD"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Yaşamla ölüm arasında bir kütüphane var,\" dedi. \"Bu kütüphanedeki raflar sonsuza kadar gider. Her kitap yaşamış olabileceğin başka bir hayatı yaşama şansını sunar sana. Farklı seçimler yapmış olsan, şu an nasıl bir hayatın olacağını görürsün.Pişmanlıklarını telafi etme şansın olsaydı, bazı konularda farklı davranır mıydın?",
                            ImageUrl = "",
                            Price = 72.359999999999999,
                            Title = "Gece Yarısı Kütüphanesi"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Jack London, 1912 yılında İngiltere'de London Magazine'de yayımlanmaya başlayan Kızıl Veba yapıtıyla \"kıyamet sonrası\" edebiyatın öncüleri arasına girmiştir.",
                            ImageUrl = "",
                            Price = 15.1,
                            Title = "Kızıl Veba"
                        });
                });

            modelBuilder.Entity("Commerce.Models.Product", b =>
                {
                    b.HasOne("Commerce.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
